package filedigger;

/**
 *
 * @author Anubhav Saxena
 * anubhav@saxena.xyz
 * http://saxena.xyz
 */
public class Launcher extends javax.swing.JFrame {

    /** Creates new form Launcher */
    public Launcher() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        textline = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        javaversioning = new javax.swing.JLabel();
        aboutlabel = new javax.swing.JLabel();
        startbutton = new javax.swing.JButton();
        versioninglabel = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();
        versioninglabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("anubhav@saxena.xyz | saxena.xyz");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        title.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("FileDigger");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        textline.setForeground(new java.awt.Color(255, 255, 255));
        textline.setText("__________________________________________________________________");
        getContentPane().add(textline, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        subtitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subtitle.setForeground(new java.awt.Color(0, 204, 204));
        subtitle.setText("@author Anubhav Saxena");
        getContentPane().add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        javaversioning.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        javaversioning.setForeground(new java.awt.Color(255, 102, 51));
        javaversioning.setText("Java 1.7.0_51");
        getContentPane().add(javaversioning, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        aboutlabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        aboutlabel.setForeground(new java.awt.Color(0, 102, 255));
        aboutlabel.setText("Digs through directories and collects files");
        getContentPane().add(aboutlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        startbutton.setBackground(new java.awt.Color(204, 204, 204));
        startbutton.setForeground(new java.awt.Color(204, 0, 0));
        startbutton.setText("Launch");
        startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(startbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 90, 30));

        versioninglabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        versioninglabel.setForeground(new java.awt.Color(255, 102, 51));
        versioninglabel.setText("FileDigger v1.0");
        getContentPane().add(versioninglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filedigger/img/bimg.png"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        versioninglabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        versioninglabel2.setForeground(new java.awt.Color(255, 102, 51));
        versioninglabel2.setText("Java 1.7.0_51");
        getContentPane().add(versioninglabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
        // TODO add handling code:
    }//GEN-LAST:event_startbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Sets the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutlabel;
    private javax.swing.JLabel bgimg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel javaversioning;
    private javax.swing.JButton startbutton;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel textline;
    private javax.swing.JLabel title;
    private javax.swing.JLabel versioninglabel;
    private javax.swing.JLabel versioninglabel2;
    // End of variables declaration//GEN-END:variables

}
